### ISSUE TITLE
register_image() got an unexpected keyword argument 'virtualization_type'

### ISSUE THREAD

**Issue by jaybonci** [andsens/bootstrap-vz#48]
Steps to repro:
- Create a new EC2 micro instance (confirmed not working with ubuntu 13.10 and 12.04 official images
- Edit the ec2-ebs-debian-official-amd64-pvm.manifest.json to include valid Access Key / Secret Access Key credentials
- (I also made the disks 20G)
- Follow the instructions here: http://andsens.github.io/bootstrap-vz/index.html

You will get the following error: register_image() got an unexpected keyword argument 'virtualization_type'

> root@ip-10-234-70-4:~/bootstrap-vz# ./bootstrap-vz manifests/ec2-ebs-debian-official-amd64-pvm.manifest.json 
> Adding backports to the apt sources
> Creating workspace
> Adding default release sources
> Adding cloud-init package and sudo
> Adding grub package
> Adding image packages required for EC2
> Determining required external commands for EC2 bootstrapping
> Retrieving instance metadata
> Adding locale package to bootstrap installation
> Adding commands required bootstrapping Debian
> Checking availability of external commands
> Getting AWS credentials
> Connecting to EC2
> Determining the AMI name
> Creating the EBS volume
> Attaching the volume
> Formatting the volume
> mke2fs 1.42.8 (20-Jun-2013)
> Tuning the bootstrap volume filesystem
> Creating mountpoint for the root partition
> Mounting the root partition
> Installing Debian
> Mounting special block devices
> Generating the selected locale
> Disabling daemon autostart
> Writing aptitude sources to disk
> Updating the package cache
> Upgrading packages and fixing broken dependencies
> 
> Current default time zone: 'Etc/UTC'
> Local time is now:      Mon Mar 31 02:57:24 UTC 2014.
> Universal Time is now:  Mon Mar 31 02:57:24 UTC 2014.
> Run 'dpkg-reconfigure tzdata' if you wish to change it.
> 
> Installing packages
> Extracting templates from packages: 100%
> Moving old data out of the way
> Running depmod.
> Examining /etc/kernel/postinst.d.
> run-parts: executing /etc/kernel/postinst.d/initramfs-tools 3.2.0-4-amd64 /boot/vmlinuz-3.2.0-4-amd64
> update-initramfs: Generating /boot/initrd.img-3.2.0-4-amd64
> df: Warning: cannot read table of mounted file systems: No such file or directory
> Adding 'diversion of /etc/init/ureadahead.conf to /etc/init/ureadahead.conf.disabled by cloud-init'
> Creating SSH2 RSA key; this may take some time ...
> Creating SSH2 DSA key; this may take some time ...
> Creating SSH2 ECDSA key; this may take some time ...
> invoke-rc.d: policy-rc.d denied execution of restart.
> 
> Creating config file /etc/default/grub with new version
> df: Warning: cannot read table of mounted file systems: No such file or directory
> Enabling shadowconfig
> Disabling sshd remote host name lookup
> Configuring the DHCP client to set the nameservers
> Setting the selected timezone
> Disabling getty processes
> Setting metadata source
> Configuring network interfaces
> Creating grub config files for PVGrub
> Generating grub.cfg ...
> done
> Setting cloud.cfg modules
> Blacklisting kernel modules
> Removing hardware clock init scripts
> Disabling SSH password authentication
> Removing the hostname file
> Removing resolv.conf
> Setting username in cloud.cfg
> Adding partitions to the fstab
> Installing startup scripts
> Re-enabling daemon autostart after installation
> Securely deleting ssh hostkeys
> Removing temporary files
> Removing unused packages
> Clearing the MOTD
> Clearing the aptitude cache
> Unmounting the bootstrap volume
> Detaching the volume
> Deleting mountpoint for the bootstrap volume
> Creating a snapshot of the EBS volume
> Registering the image as an AMI
> register_image() got an unexpected keyword argument 'virtualization_type'
> Traceback (most recent call last):
>   File "/root/bootstrap-vz/base/main.py", line 66, in run
>     tasklist.run(info=bootstrap_info, dry_run=args.dry_run)
>   File "/root/bootstrap-vz/base/tasklist.py", line 59, in run
>     task.run(info)
>   File "/root/bootstrap-vz/providers/ec2/tasks/ami.py", line 125, in run
>     info.image = info.connection.register_image(**registration_params)
> TypeError: register_image() got an unexpected keyword argument 'virtualization_type'
> Rolling back
> Deleting the volume
> Deleting workspace
> Successfully completed rollback

Please let me know what I can do to help!
