### ISSUE TITLE
Error Installing ENA networking kernel driver using DKMS 

### ISSUE THREAD

**Issue by joeweoj** [andsens/bootstrap-vz#399]
Hi.

While trying to build a Debian Jessie image I encountered the following fatal error when the build attempted to install the ENA networking kernel driver using DKMS which appears to use the amzn-drivers:

> 2017-09-26 09:29:00,185 - bootstrapvz.base.tasklist.run - INFO - Installing ENA networking kernel driver using DKMS
> 2017-09-26 09:29:00,233 - bootstrapvz.common.tools.root.git.handle_stderr - ERROR - Cloning into '/target/5521ed29/root/usr/src/amzn-drivers-1.0.0'...
> 2017-09-26 09:29:07,728 - bootstrapvz.common.tools.root.chroot.handle_stderr - ERROR - Error! Bad return status for module build on kernel: 3.16.0-4-amd64 (x86_64)
> 2017-09-26 09:29:07,728 - bootstrapvz.common.tools.root.chroot.handle_stderr - ERROR - Consult /var/lib/dkms/amzn-drivers/1.0.0/build/make.log for more information.

Contents of `make.log`

> root@box:~# chroot /target/cae4cc9e/root
> root@box:/# cat /var/lib/dkms/amzn-drivers/1.0.0/build/make.log
> DKMS make.log for amzn-drivers-1.0.0 for kernel 3.16.0-4-amd64 (x86_64)
> Tue 26 Sep 10:01:05 UTC 2017
> make: Entering directory '/var/lib/dkms/amzn-drivers/1.0.0/build/kernel/linux/ena'
> make -C /lib/modules/3.16.0-4-amd64/build M=/var/lib/dkms/amzn-drivers/1.0.0/build/kernel/linux/ena modules
> make[1]: Entering directory '/usr/src/linux-headers-3.16.0-4-amd64'
> make[1]: Entering directory `/usr/src/linux-headers-3.16.0-4-amd64'
>   CC [M]  /var/lib/dkms/amzn-drivers/1.0.0/build/kernel/linux/ena/ena_netdev.o
> /var/lib/dkms/amzn-drivers/1.0.0/build/kernel/linux/ena/ena_netdev.c: In function ‘ena_probe’:
> /var/lib/dkms/amzn-drivers/1.0.0/build/kernel/linux/ena/ena_netdev.c:3480:3: error: implicit declaration of function ‘devm_ioremap_wc’ [-Werror=implicit-function-declaration]
>    ena_dev->mem_bar = devm_ioremap_wc(&pdev->dev,
>    ^
> compilation terminated due to -Wfatal-errors.
> cc1: some warnings being treated as errors
> /usr/src/linux-headers-3.16.0-4-common/scripts/Makefile.build:262: recipe for target '/var/lib/dkms/amzn-drivers/1.0.0/build/kernel/linux/ena/ena_netdev.o' failed
> make[4]: *** [/var/lib/dkms/amzn-drivers/1.0.0/build/kernel/linux/ena/ena_netdev.o] Error 1
> /usr/src/linux-headers-3.16.0-4-common/Makefile:1354: recipe for target '_module_/var/lib/dkms/amzn-drivers/1.0.0/build/kernel/linux/ena' failed
> make[3]: *** [_module_/var/lib/dkms/amzn-drivers/1.0.0/build/kernel/linux/ena] Error 2
> Makefile:181: recipe for target 'sub-make' failed
> make[2]: *** [sub-make] Error 2
> Makefile:8: recipe for target 'all' failed
> make[1]: *** [all] Error 2
> make[1]: Leaving directory '/usr/src/linux-headers-3.16.0-4-amd64'
> Makefile:19: recipe for target 'all' failed
> make: *** [all] Error 2
> make: Leaving directory '/var/lib/dkms/amzn-drivers/1.0.0/build/kernel/linux/ena'
> root@box:/#

I have resolved this issue (purely to unblock me) by hardcoding a different version of the amzn-drivers. By default it seems to pull master, but by pinning it to [ena_linux_1.2.0](https://github.com/amzn/amzn-drivers/releases/tag/ena_linux_1.2.0).

My hacky fix can be found on my fork [here](https://github.com/joeweoj/bootstrap-vz/commit/b286bb8adc4ad0a488449529746fbad443da62fc). I didn't make it a pull request as, like i said, hacky, but thought you'd like to know about this issue and hopefully google will index this issue for any unfortunate souls similarly banging their head against a brick wall.

Let me know if you need any further information. Thanks

**Comment by andsens** [comment]
Thanks for reporting this. Did you create an issue with amazon, I'm sure they'd like to know about it.  
Regardless, pinning the version to the latest stable and then updating it periodically might be a good idea. Then again, it'll just increase the workload, being able to override the version through the manifest as a provider specific setting might be the best option.

**Comment by joeweoj** [comment]
Issue raised under amazn-drivers [here](https://github.com/amzn/amzn-drivers/issues/40).

Cheers

**Comment by CMeza99** [comment]
I think PR #448 addresses this issue, and is implement how @andsens suggested.

**Comment by andsens** [comment]
@joeweoj, the PR is merged. Care to retry and report back? :-)
